# Phase 07 — Unimodal Contribution Analysis

Executed initialization and read-only upstream audit. This notebook performs no model training, hypervector generation, prediction, OOF generation, row deletion, or fitted preprocessing.

## 1. Environment information

In [1]:
from pathlib import Path
import json, platform, sys
PHASE_DIR = Path.cwd().resolve()
assert PHASE_DIR.name == 'phase_07_unimodal_contribution'
sys.path.insert(0, str(PHASE_DIR / 'scripts'))
from initialize_phase07 import collect_audit
audit = collect_audit()
print(json.dumps({'python': sys.version, 'platform': platform.platform(), 'phase_dir': str(PHASE_DIR)}, indent=2))

{
  "python": "3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]",
  "platform": "Windows-11-10.0.26200-SP0",
  "phase_dir": "E:\\hdc-vr-pilot\\experiments\\phase_07_unimodal_contribution"
}

## 2. Required upstream file existence

In [2]:
print(json.dumps(audit['upstream_existence'], indent=2)); assert all(audit['upstream_existence'].values())

{
  "plan": true,
  "primary_data": true,
  "frozen_folds": true,
  "feature_groups": true,
  "primary_features": true,
  "phase06_freeze": true,
  "phase06_classification": true,
  "phase06_regression": true,
  "phase06_artifact_manifest": true,
  "phase06_selection_audit": true
}

## 3. Primary data SHA-256

In [3]:
print(audit['hashes']['primary_data']); assert audit['data_checks']['primary_data_checksum_pass']

0a2aef89c01b43c3a4e5afe40b96797784627665490982731b2541f96b45fc44

## 4. Frozen fold SHA-256

In [4]:
print(audit['hashes']['frozen_folds']); assert audit['data_checks']['frozen_fold_checksum_pass']

e4dc943af21851bace49345f6336f9c88f82613ca3a26b3c433efe7dfb041f6f

## 5. Phase 06 core configuration SHA-256

In [5]:
keys = ['phase06_freeze', 'phase06_classification', 'phase06_regression']
print(json.dumps({key: audit['hashes'][key] for key in keys}, indent=2))
assert audit['phase06_checks']['freeze_checksum_pass']
assert audit['phase06_checks']['classification_checksum_pass']
assert audit['phase06_checks']['regression_checksum_pass']

{
  "phase06_freeze": "cd94acdf0bcb463b5f48a7c84110a23059899b6b5bf156131694827d7d7bde66",
  "phase06_classification": "174a99de2d993acdea49fdebc9647b28db4648ada2bea7a33f620f4677f031a4",
  "phase06_regression": "acde51709971d57c76eefaffcf1ecd571a4d4c5c36f8d76edf39841c5e7065b8"
}

## 6. Modeling rows, subjects, and Primary features

In [6]:
checks = audit['data_checks']
print(json.dumps({key: checks[key] for key in ['modeling_rows','subjects','primary_predictive_features','unique_run_key']}, indent=2))
assert checks['modeling_rows'] == 419 and checks['subjects'] == 35
assert checks['primary_predictive_features'] == 1176 and checks['unique_run_key'] == 419

{
  "modeling_rows": 419,
  "subjects": 35,
  "primary_predictive_features": 1176,
  "unique_run_key": 419
}

## 7. Classification and regression targets

In [7]:
print(json.dumps({key: checks[key] for key in ['target_class_values','target_class_missing','target_score_values','target_score_missing']}, indent=2))
assert checks['target_class_values'] == [0,1,2,3] and checks['target_class_missing'] == 0
assert checks['target_score_values'] == [1.0,2.0,3.0,4.0] and checks['target_score_missing'] == 0

{
  "target_class_values": [
    0,
    1,
    2,
    3
  ],
  "target_class_missing": 0,
  "target_score_values": [
    1.0,
    2.0,
    3.0,
    4.0
  ],
  "target_score_missing": 0
}

## 8. run_key uniqueness and fold alignment

In [8]:
print(json.dumps({key: checks[key] for key in ['fold_assignment_rows','fold_assignment_unique_run_key','run_key_one_to_one_alignment']}, indent=2))
assert checks['fold_assignment_rows'] == checks['fold_assignment_unique_run_key'] == 419
assert checks['run_key_one_to_one_alignment']

{
  "fold_assignment_rows": 419,
  "fold_assignment_unique_run_key": 419,
  "run_key_one_to_one_alignment": true
}

## 9. Outer-fold subject isolation

In [9]:
print(json.dumps(audit['outer_fold_audits'], indent=2)); assert checks['outer_subject_isolation_pass']

[
  {
    "outer_fold": 1,
    "train_rows": 335,
    "test_rows": 84,
    "train_subjects": 28,
    "test_subjects": 7,
    "subject_overlap": [],
    "subject_isolation_pass": true
  },
  {
    "outer_fold": 2,
    "train_rows": 335,
    "test_rows": 84,
    "train_subjects": 28,
    "test_subjects": 7,
    "subject_overlap": [],
    "subject_isolation_pass": true
  },
  {
    "outer_fold": 3,
    "train_rows": 335,
    "test_rows": 84,
    "train_subjects": 28,
    "test_subjects": 7,
    "subject_overlap": [],
    "subject_isolation_pass": true
  },
  {
    "outer_fold": 4,
    "train_rows": 335,
    "test_rows": 84,
    "train_subjects": 28,
    "test_subjects": 7,
    "subject_overlap": [],
    "subject_isolation_pass": true
  },
  {
    "outer_fold": 5,
    "train_rows": 336,
    "test_rows": 83,
    "train_subjects": 28,
    "test_subjects": 7,
    "subject_overlap": [],
    "subject_isolation_pass": true
  }
]

## 10. Inner GroupKFold feasibility

In [10]:
print(json.dumps(audit['inner_groupkfold_audits'], indent=2)); assert checks['inner_groupkfold_3_feasibility_pass']

[
  {
    "outer_fold": 1,
    "outer_training_subjects": 28,
    "inner_splits": 3,
    "all_inner_subject_isolation_pass": true,
    "groupkfold_3_feasible": true
  },
  {
    "outer_fold": 2,
    "outer_training_subjects": 28,
    "inner_splits": 3,
    "all_inner_subject_isolation_pass": true,
    "groupkfold_3_feasible": true
  },
  {
    "outer_fold": 3,
    "outer_training_subjects": 28,
    "inner_splits": 3,
    "all_inner_subject_isolation_pass": true,
    "groupkfold_3_feasible": true
  },
  {
    "outer_fold": 4,
    "outer_training_subjects": 28,
    "inner_splits": 3,
    "all_inner_subject_isolation_pass": true,
    "groupkfold_3_feasible": true
  },
  {
    "outer_fold": 5,
    "outer_training_subjects": 28,
    "inner_splits": 3,
    "all_inner_subject_isolation_pass": true,
    "groupkfold_3_feasible": true
  }
]

## 11. Frozen five-modality membership and counts

In [11]:
print(json.dumps(audit['modality_checks']['feature_counts'], indent=2)); assert audit['modality_checks']['expected_counts_pass']

{
  "physiological_features": 233,
  "eye_tracking_features": 416,
  "head_movement_features": 159,
  "flight_parameter_features": 326,
  "body_movement": 42
}

## 12. Modality disjointness and complete Primary coverage

In [12]:
mapping = audit['modality_checks']
print(json.dumps({key: mapping[key] for key in ['feature_union_count','disjointness_pass','union_coverage_pass','duplicate_memberships']}, indent=2))
assert mapping['feature_union_count'] == 1176 and mapping['disjointness_pass'] and mapping['union_coverage_pass']

{
  "feature_union_count": 1176,
  "disjointness_pass": true,
  "union_coverage_pass": true,
  "duplicate_memberships": []
}

## 13. Modality-level missingness and availability audit

In [13]:
summary = [{
  'modality': item['modality'], 'feature_count': item['feature_count'],
  'fully_missing_rows': item['fully_missing_rows'],
  'subjects_with_available_data': item['subjects_with_available_data'],
  'target_class_distribution_available_rows': item['target_class_distribution_available_rows'],
  'target_score_distribution_available_rows': item['target_score_distribution_available_rows'],
  'outer_fold_details': item['outer_fold_details']} for item in audit['modality_audits']]
print(json.dumps(summary, indent=2))
assert all(all(f['train_has_available_modality_data'] and f['test_has_available_modality_data'] for f in item['outer_fold_details']) for item in audit['modality_audits'])

[
  {
    "modality": "physiological_features",
    "feature_count": 233,
    "fully_missing_rows": 0,
    "subjects_with_available_data": 35,
    "target_class_distribution_available_rows": {
      "0": 104,
      "1": 106,
      "2": 104,
      "3": 105
    },
    "target_score_distribution_available_rows": {
      "1.0": 104,
      "2.0": 106,
      "3.0": 104,
      "4.0": 105
    },
    "outer_fold_details": [
      {
        "outer_fold": 1,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 2,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 3,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 4,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 5,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      }
    ]
  },
  {
    "modality": "eye_tracking_features",
    "feature_count": 416,
    "fully_missing_rows": 14,
    "subjects_with_available_data": 34,
    "target_class_distribution_available_rows": {
      "0": 100,
      "1": 103,
      "2": 100,
      "3": 102
    },
    "target_score_distribution_available_rows": {
      "1.0": 100,
      "2.0": 103,
      "3.0": 100,
      "4.0": 102
    },
    "outer_fold_details": [
      {
        "outer_fold": 1,
        "fully_missing_rows_all": 2,
        "fully_missing_rows_train": 12,
        "fully_missing_rows_test": 2,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 2,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 14,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 3,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 14,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 4,
        "fully_missing_rows_all": 12,
        "fully_missing_rows_train": 2,
        "fully_missing_rows_test": 12,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 5,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 14,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      }
    ]
  },
  {
    "modality": "head_movement_features",
    "feature_count": 159,
    "fully_missing_rows": 0,
    "subjects_with_available_data": 35,
    "target_class_distribution_available_rows": {
      "0": 104,
      "1": 106,
      "2": 104,
      "3": 105
    },
    "target_score_distribution_available_rows": {
      "1.0": 104,
      "2.0": 106,
      "3.0": 104,
      "4.0": 105
    },
    "outer_fold_details": [
      {
        "outer_fold": 1,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 2,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 3,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 4,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 5,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      }
    ]
  },
  {
    "modality": "flight_parameter_features",
    "feature_count": 326,
    "fully_missing_rows": 0,
    "subjects_with_available_data": 35,
    "target_class_distribution_available_rows": {
      "0": 104,
      "1": 106,
      "2": 104,
      "3": 105
    },
    "target_score_distribution_available_rows": {
      "1.0": 104,
      "2.0": 106,
      "3.0": 104,
      "4.0": 105
    },
    "outer_fold_details": [
      {
        "outer_fold": 1,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 2,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 3,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 4,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 5,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 0,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      }
    ]
  },
  {
    "modality": "body_movement",
    "feature_count": 42,
    "fully_missing_rows": 29,
    "subjects_with_available_data": 33,
    "target_class_distribution_available_rows": {
      "0": 97,
      "1": 99,
      "2": 96,
      "3": 98
    },
    "target_score_distribution_available_rows": {
      "1.0": 97,
      "2.0": 99,
      "3.0": 96,
      "4.0": 98
    },
    "outer_fold_details": [
      {
        "outer_fold": 1,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 29,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 2,
        "fully_missing_rows_all": 12,
        "fully_missing_rows_train": 17,
        "fully_missing_rows_test": 12,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 3,
        "fully_missing_rows_all": 5,
        "fully_missing_rows_train": 24,
        "fully_missing_rows_test": 5,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 4,
        "fully_missing_rows_all": 12,
        "fully_missing_rows_train": 17,
        "fully_missing_rows_test": 12,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      },
      {
        "outer_fold": 5,
        "fully_missing_rows_all": 0,
        "fully_missing_rows_train": 29,
        "fully_missing_rows_test": 0,
        "train_has_available_modality_data": true,
        "test_has_available_modality_data": true
      }
    ]
  }
]

## 14. Performance, control-input, and unverified exclusions

In [14]:
exclusions = {key: mapping[key] for key in ['performance_primary_intersection_count','control_input_feature_count','unverified_feature_count','body_movement_status','body_movement_verified']}
print(json.dumps(exclusions, indent=2))
assert mapping['performance_primary_intersection_count'] == 0
assert mapping['control_input_feature_count'] == mapping['unverified_feature_count'] == 0
assert mapping['body_movement_verified']

{
  "performance_primary_intersection_count": 0,
  "control_input_feature_count": 0,
  "unverified_feature_count": 0,
  "body_movement_status": "VERIFIED_BODY_MOVEMENT:42",
  "body_movement_verified": true
}

## 15. Frozen Phase 06 classification interface

In [15]:
classification = audit['phase06_classification']
print(json.dumps({key: classification[key] for key in ['selected_variant','selected_variant_name','selected_fixed_dimension','levels','feature_k','structure_selection_policy','selection_evidence','single_seed_selected']}, indent=2))
assert audit['phase06_checks']['classification_interface_pass']

{
  "selected_variant": "hybrid",
  "selected_variant_name": "HDC+OnlineHD Hybrid",
  "selected_fixed_dimension": 5000,
  "levels": 51,
  "feature_k": 50,
  "structure_selection_policy": "fold-local inner-CV selection under the frozen Quick Screen grid",
  "selection_evidence": "INNER_CV_ONLY",
  "single_seed_selected": false
}

## 16. Frozen Phase 06 regression interface

In [16]:
regression = audit['phase06_regression']
print(json.dumps({key: regression[key] for key in ['selected_variant','selected_regression_head','selected_fixed_dimension','levels','feature_k','parameter_policy','selection_evidence','single_seed_selected']}, indent=2))
print('Target: bounded difficulty-induced workload proxy regression')
assert audit['phase06_checks']['regression_interface_pass']
assert not audit['phase06_checks']['outer_oof_read_for_selection']

{
  "selected_variant": "common_ridge",
  "selected_regression_head": "COMMON_ENCODER_READOUT_BASELINE",
  "selected_fixed_dimension": 10000,
  "levels": 51,
  "feature_k": 50,
  "parameter_policy": "fold-local inner-CV temperature or Ridge alpha selection",
  "selection_evidence": "INNER_CV_ONLY",
  "single_seed_selected": false
}
Target: bounded difficulty-induced workload proxy regression

## 17. Initialization artifact existence and JSON parseability

In [17]:
required = [
 'configs/phase07_experiment_contract.json','configs/phase07_environment.json','configs/phase07_upstream_interface.json',
 'manifests/phase07_input_manifest.json','manifests/phase07_modality_feature_manifest.json',
 'audits/phase07_input_and_fold_audit.json','audits/phase07_modality_mapping_audit.json',
 'audits/phase07_phase06_freeze_interface_audit.json','audits/phase07_initialization_artifact_audit.json',
 'audits/phase07_notebook_persistence_audit.json']
artifact_checks = {}
for relative in required:
    path = PHASE_DIR / relative
    artifact_checks[relative] = {'exists': path.is_file(), 'json_parseable': False}
    if path.is_file():
        json.loads(path.read_text(encoding='utf-8'))
        artifact_checks[relative]['json_parseable'] = True
print(json.dumps(artifact_checks, indent=2))
assert all(item['exists'] and item['json_parseable'] for item in artifact_checks.values())

{
  "configs/phase07_experiment_contract.json": {
    "exists": true,
    "json_parseable": true
  },
  "configs/phase07_environment.json": {
    "exists": true,
    "json_parseable": true
  },
  "configs/phase07_upstream_interface.json": {
    "exists": true,
    "json_parseable": true
  },
  "manifests/phase07_input_manifest.json": {
    "exists": true,
    "json_parseable": true
  },
  "manifests/phase07_modality_feature_manifest.json": {
    "exists": true,
    "json_parseable": true
  },
  "audits/phase07_input_and_fold_audit.json": {
    "exists": true,
    "json_parseable": true
  },
  "audits/phase07_modality_mapping_audit.json": {
    "exists": true,
    "json_parseable": true
  },
  "audits/phase07_phase06_freeze_interface_audit.json": {
    "exists": true,
    "json_parseable": true
  },
  "audits/phase07_initialization_artifact_audit.json": {
    "exists": true,
    "json_parseable": true
  },
  "audits/phase07_notebook_persistence_audit.json": {
    "exists": true,
    "json_parseable": true
  }
}

## 18. Final initialization summary

In [18]:
summary = {
 'initialization_gates_without_notebook_persistence_pass': audit['initialization_gates_without_notebook_persistence_pass'],
 'phase_status': 'PENDING_CONTRACT_FREEZE',
 'hdc_training_executed': audit['hdc_training_executed'],
 'ready_for_contract_freeze_subject_to_notebook_persistence': audit['initialization_gates_without_notebook_persistence_pass'],
 'ready_for_modeling': False}
print(json.dumps(summary, indent=2))
assert summary['initialization_gates_without_notebook_persistence_pass']
assert not summary['hdc_training_executed'] and not summary['ready_for_modeling']

{
  "initialization_gates_without_notebook_persistence_pass": true,
  "phase_status": "PENDING_CONTRACT_FREEZE",
  "hdc_training_executed": false,
  "ready_for_contract_freeze_subject_to_notebook_persistence": true,
  "ready_for_modeling": false
}

## Phase Validation Summary

**VERIFIED**: frozen inputs, checksums, row/subject/feature/target counts, run-key alignment, outer isolation, inner feasibility, modality mapping, exclusions, and Phase 06 interfaces.

**NOT VERIFIED**: the intentionally unresolved Phase 07 Contract Freeze decisions.

**WARNINGS**: control input is unavailable; performance features are excluded; no modeling is authorized.

**KEY RESULTS**: five disjoint modalities cover all 1176 Primary features.

**OUTPUT FILES**: Phase 07 configs, manifests, audits, documentation, and this executed notebook.

**NEXT PHASE REQUIREMENTS**: Phase 07 Contract Freeze. Do not start modeling.

# Phase 07 Contract Freeze

Static contract freeze only. No model training, hypervector generation, outer-test prediction, or OOF generation is executed.

In [19]:
contract = json.loads((PHASE_DIR / 'configs/phase07_frozen_unimodal_contract.json').read_text(encoding='utf-8'))
stats_contract = json.loads((PHASE_DIR / 'configs/phase07_statistical_analysis_contract.json').read_text(encoding='utf-8'))
execution = json.loads((PHASE_DIR / 'configs/phase07_execution_manifest.json').read_text(encoding='utf-8'))
print(json.dumps({'status': contract['status'], 'primary_analysis': contract['primary_analysis'], 'training_executed': contract['training_executed']}, indent=2))

{
  "status": "CONTRACT_FROZEN_NOT_TRAINED",
  "primary_analysis": "FULL_COHORT_419_RUNS_WITH_FOLD_LOCAL_MISSINGNESS_HANDLING",
  "training_executed": false
}

## Frozen modalities

In [20]:
print(json.dumps(contract['modalities'], indent=2)); assert len(contract['modalities']) == 5 and sum(item['feature_count'] for item in contract['modalities']) == 1176

[
  {
    "name": "physiological_features",
    "feature_count": 233,
    "membership_source": "manifests/phase07_modality_feature_manifest.json",
    "fusion_permitted": false
  },
  {
    "name": "eye_tracking_features",
    "feature_count": 416,
    "membership_source": "manifests/phase07_modality_feature_manifest.json",
    "fusion_permitted": false
  },
  {
    "name": "head_movement_features",
    "feature_count": 159,
    "membership_source": "manifests/phase07_modality_feature_manifest.json",
    "fusion_permitted": false
  },
  {
    "name": "flight_parameter_features",
    "feature_count": 326,
    "membership_source": "manifests/phase07_modality_feature_manifest.json",
    "fusion_permitted": false
  },
  {
    "name": "body_movement",
    "feature_count": 42,
    "membership_source": "manifests/phase07_modality_feature_manifest.json",
    "fusion_permitted": false
  }
]

## Full-cohort and fully-missing modality policy

In [21]:
print(json.dumps({'sample_policy': contract['sample_and_fold_policy'], 'missingness_policy': contract['missingness_policy']}, indent=2)); assert contract['sample_and_fold_policy']['retain_all_modeling_rows']; assert contract['missingness_policy']['fully_missing_rows_retained']

{
  "sample_policy": {
    "modeling_rows": 419,
    "run_key_alignment_required": true,
    "outer_folds": 5,
    "outer_split_source": "E:\\hdc-vr-pilot\\experiments\\phase_03_multimodal_dataset_labeling\\data\\fold_assignments.csv",
    "outer_fold_regeneration_prohibited": true,
    "retain_all_modeling_rows": true,
    "row_deletion_prohibited": true,
    "outer_training_fit_only": true,
    "outer_test_transform_and_predict_only": true
  },
  "missingness_policy": {
    "status": "FROZEN",
    "fully_missing_rows_by_modality": {
      "physiological_features": 0,
      "eye_tracking_features": 14,
      "head_movement_features": 0,
      "flight_parameter_features": 0,
      "body_movement": 29
    },
    "fully_missing_rows_retained": true,
    "imputer_fit_scope": "outer-training or inner-training rows only, as appropriate",
    "missing_indicators_required": true,
    "global_statistics_prohibited": true,
    "global_nan_to_zero_prohibited": true,
    "availability_stratified_diagnostics_required": true,
    "diagnostic_strata": [
      "modality_available",
      "modality_fully_missing"
    ],
    "diagnostics_do_not_replace_full_cohort": true,
    "diagnostics_not_for_retraining_or_selection": true
  }
}

## Frozen classification interface

In [22]:
print(json.dumps(contract['classification'], indent=2)); assert contract['classification']['model'] == 'HDC+OnlineHD Hybrid' and len(contract['classification']['fold_structures']) == 5

{
  "model": "HDC+OnlineHD Hybrid",
  "selected_variant": "hybrid",
  "dimension": 5000,
  "levels": 51,
  "requested_feature_k": 50,
  "representation": "bipolar",
  "similarity": "cosine",
  "seeds": [
    42,
    43,
    44,
    45,
    46
  ],
  "classes": [
    0,
    1,
    2,
    3
  ],
  "primary_metric": "Macro-F1",
  "fold_structures": [
    {
      "outer_fold": 1,
      "centroids_per_class": 3,
      "epochs": 1,
      "learning_rate": 0.1,
      "margin_threshold": 0.0
    },
    {
      "outer_fold": 2,
      "centroids_per_class": 2,
      "epochs": 1,
      "learning_rate": 0.05,
      "margin_threshold": 0.0
    },
    {
      "outer_fold": 3,
      "centroids_per_class": 2,
      "epochs": 3,
      "learning_rate": 0.05,
      "margin_threshold": 0.0
    },
    {
      "outer_fold": 4,
      "centroids_per_class": 2,
      "epochs": 3,
      "learning_rate": 0.1,
      "margin_threshold": 0.1
    },
    {
      "outer_fold": 5,
      "centroids_per_class": 3,
      "epochs": 1,
      "learning_rate": 0.1,
      "margin_threshold": 0.0
    }
  ],
  "structure_source": "E:\\hdc-vr-pilot\\experiments\\phase_06_hdc_variant_screening\\configs\\phase06_best_classification_hdc.json",
  "metric_names": [
    "macro_f1",
    "balanced_accuracy",
    "accuracy",
    "per_class_recall",
    "severe_error_rate",
    "confusion_matrix"
  ],
  "severe_error_definition": "abs(predicted_class - target_class) >= 2",
  "metric_labels": [
    0,
    1,
    2,
    3
  ],
  "zero_division": 0,
  "runs_per_modality": 25,
  "total_runs": 125,
  "reselection_prohibited": true,
  "single_best_seed_selection_prohibited": true
}

## Frozen regression interface

In [23]:
print(json.dumps(contract['regression'], indent=2)); assert contract['regression']['head'] == 'COMMON_ENCODER_READOUT_BASELINE' and contract['regression']['ridge_alpha'] == 0.01

{
  "selected_variant": "common_ridge",
  "head": "COMMON_ENCODER_READOUT_BASELINE",
  "dimension": 10000,
  "levels": 51,
  "requested_feature_k": 50,
  "seeds": [
    42,
    43,
    44,
    45,
    46
  ],
  "target": "target_score",
  "target_range": [
    1.0,
    4.0
  ],
  "target_description": "bounded difficulty-induced workload proxy regression",
  "primary_metric": "bounded_mae",
  "ridge_alpha": 0.01,
  "fold_seed_parameter_policy": [
    {
      "outer_fold": 1,
      "seed_parameters": [
        {
          "ridge_alpha": 0.01,
          "seed": 42
        },
        {
          "ridge_alpha": 0.01,
          "seed": 43
        },
        {
          "ridge_alpha": 0.01,
          "seed": 44
        },
        {
          "ridge_alpha": 0.01,
          "seed": 45
        },
        {
          "ridge_alpha": 0.01,
          "seed": 46
        }
      ]
    },
    {
      "outer_fold": 2,
      "seed_parameters": [
        {
          "ridge_alpha": 0.01,
          "seed": 42
        },
        {
          "ridge_alpha": 0.01,
          "seed": 43
        },
        {
          "ridge_alpha": 0.01,
          "seed": 44
        },
        {
          "ridge_alpha": 0.01,
          "seed": 45
        },
        {
          "ridge_alpha": 0.01,
          "seed": 46
        }
      ]
    },
    {
      "outer_fold": 3,
      "seed_parameters": [
        {
          "ridge_alpha": 0.01,
          "seed": 42
        },
        {
          "ridge_alpha": 0.01,
          "seed": 43
        },
        {
          "ridge_alpha": 0.01,
          "seed": 44
        },
        {
          "ridge_alpha": 0.01,
          "seed": 45
        },
        {
          "ridge_alpha": 0.01,
          "seed": 46
        }
      ]
    },
    {
      "outer_fold": 4,
      "seed_parameters": [
        {
          "ridge_alpha": 0.01,
          "seed": 42
        },
        {
          "ridge_alpha": 0.01,
          "seed": 43
        },
        {
          "ridge_alpha": 0.01,
          "seed": 44
        },
        {
          "ridge_alpha": 0.01,
          "seed": 45
        },
        {
          "ridge_alpha": 0.01,
          "seed": 46
        }
      ]
    },
    {
      "outer_fold": 5,
      "seed_parameters": [
        {
          "ridge_alpha": 0.01,
          "seed": 42
        },
        {
          "ridge_alpha": 0.01,
          "seed": 43
        },
        {
          "ridge_alpha": 0.01,
          "seed": 44
        },
        {
          "ridge_alpha": 0.01,
          "seed": 45
        },
        {
          "ridge_alpha": 0.01,
          "seed": 46
        }
      ]
    }
  ],
  "prediction_fields": [
    "prediction_raw",
    "prediction_bounded",
    "residual_bounded"
  ],
  "prediction_bounded_rule": "clip(prediction_raw, 1.0, 4.0)",
  "metric_names": [
    "bounded_mae",
    "raw_mae",
    "bounded_rmse",
    "bounded_r2",
    "bounded_spearman",
    "per_target_level_mae"
  ],
  "runs_per_modality": 25,
  "total_runs": 125,
  "parameter_reselection_prohibited": true,
  "single_best_seed_selection_prohibited": true
}

## Effective feature-k rule

In [24]:
print(json.dumps(contract['preprocessing'], indent=2)); assert contract['preprocessing']['effective_feature_k_rule'] == 'min(50, post_variance_feature_count)'

{
  "fit_scope": "fold-local training data only",
  "ordered_steps": [
    {
      "step": 1,
      "operation": "SimpleImputer",
      "parameters": {
        "strategy": "median",
        "add_indicator": true,
        "keep_empty_features": true
      }
    },
    {
      "step": 2,
      "operation": "VarianceThreshold",
      "parameters": {
        "threshold": 0.0
      }
    },
    {
      "step": 3,
      "operation": "StandardScaler",
      "parameters": {
        "statistics": "current training fold only"
      }
    },
    {
      "step": 4,
      "operation": "SelectKBest",
      "parameters": {
        "score_func": "f_classif"
      }
    }
  ],
  "regression_reuses_f_classif": true,
  "requested_feature_k": 50,
  "effective_feature_k_rule": "min(50, post_variance_feature_count)",
  "required_run_records": [
    "requested_feature_k",
    "post_variance_feature_count",
    "effective_feature_k",
    "selected_feature_names",
    "missing_indicator_feature_names"
  ]
}

## Seeds and expected run counts

In [25]:
print(json.dumps({'seeds': contract['randomness']['seeds'], 'expected_model_runs': contract['expected_model_runs'], 'execution_manifest': execution}, indent=2)); assert execution['total_model_runs'] == 250 and execution['completed_runs'] in [0, 250]

{
  "seeds": [
    42,
    43,
    44,
    45,
    46
  ],
  "expected_model_runs": {
    "classification": 125,
    "regression": 125,
    "total": 250
  },
  "execution_manifest": {
    "phase": "07",
    "status": "FROZEN",
    "created_at_utc": "2026-08-20T18:05:58.896065+00:00",
    "modalities": 5,
    "modality_names": [
      "physiological_features",
      "eye_tracking_features",
      "head_movement_features",
      "flight_parameter_features",
      "body_movement"
    ],
    "outer_folds": 5,
    "evaluation_seeds": [
      42,
      43,
      44,
      45,
      46
    ],
    "evaluation_seed_count": 5,
    "classification_runs": 125,
    "regression_runs": 125,
    "total_model_runs": 250,
    "checkpoint_granularity": "modality/task/fold/seed",
    "resume_policy": "reuse only audit-PASS checkpoints",
    "completed_runs": 250,
    "training_executed": true,
    "prediction_files_generated": 250,
    "oof_files_generated": 0,
    "executor_invoked": true,
    "last_updated_utc": "2026-08-20T18:21:08.667820+00:00",
    "completed_classification_runs": 125,
    "completed_regression_runs": 125,
    "executor_completed": true,
    "canonical_oof_generated": true,
    "canonical_classification_rows": 2095,
    "canonical_regression_rows": 2095,
    "finalized_at_utc": "2026-08-20T18:49:14.421635+00:00"
  }
}

## Canonical OOF aggregation

In [26]:
print(json.dumps(contract['oof_aggregation'], indent=2)); assert contract['oof_aggregation']['status'] == 'FROZEN'

{
  "status": "FROZEN",
  "seed_level_rows_per_task": 10475,
  "seed_level_rows_total": 20950,
  "canonical_rows_per_task": 2095,
  "classification": {
    "group_key": [
      "modality",
      "run_key"
    ],
    "rule": "arithmetic mean of the five seed class scores, then argmax",
    "argmax_tie": "smaller target_class",
    "true_label_tiebreak_prohibited": true
  },
  "regression": {
    "group_key": [
      "modality",
      "run_key"
    ],
    "rule": "arithmetic mean of five prediction_raw values, then clip to [1.0, 4.0]",
    "canonical_metrics_recomputed_from_aggregated_predictions": true
  },
  "mean_of_seed_metrics_not_canonical": true
}

## Separate modality ranking rules

In [27]:
print(json.dumps(contract['ranking'], indent=2)); assert contract['ranking']['classification']['status'] == contract['ranking']['regression']['status'] == 'FROZEN'

{
  "classification": {
    "status": "FROZEN",
    "cohort": "all 419 canonical OOF rows",
    "ordered_criteria": [
      "macro_f1 descending",
      "balanced_accuracy descending",
      "severe_error_rate ascending",
      "seed_macro_f1_sample_sd ascending"
    ],
    "tie_tolerance": 1e-12,
    "remaining_exact_tie": "shared rank; modality-name display order only"
  },
  "regression": {
    "status": "FROZEN",
    "cohort": "all 419 canonical OOF rows",
    "ordered_criteria": [
      "bounded_mae ascending",
      "bounded_rmse ascending",
      "bounded_spearman descending",
      "seed_bounded_mae_sample_sd ascending"
    ],
    "tie_tolerance": 1e-12,
    "remaining_exact_tie": "shared rank; modality-name display order only"
  },
  "combined_best_modality_prohibited": true,
  "availability_strata_not_for_ranking": true
}

## Subject-level statistical-analysis rules

In [28]:
print(json.dumps(stats_contract, indent=2)); assert stats_contract['statistical_unit'] == 'subject' and stats_contract['bootstrap']['repetitions'] == 2000

{
  "phase": "07",
  "contract_version": "phase07_statistical_analysis_contract_v1",
  "status": "FROZEN_NOT_EXECUTED",
  "statistical_unit": "subject",
  "subjects": 35,
  "run_as_independent_unit_prohibited": true,
  "paired_analysis": true,
  "bootstrap": {
    "repetitions": 2000,
    "seed": 42,
    "confidence_interval": "percentile 95%",
    "shared_subject_resamples_for_all_models": true,
    "resampled_subject_includes_all_oof_runs": true,
    "classification_metrics": [
      "macro_f1",
      "balanced_accuracy",
      "severe_error_rate"
    ],
    "regression_metrics": [
      "bounded_mae",
      "bounded_rmse"
    ]
  },
  "overall_unimodal_comparison": {
    "test": "Friedman",
    "unit": "subject-level metrics",
    "separate_by_task": true,
    "outer_folds_as_samples_prohibited": true
  },
  "preregistered_pairwise": {
    "comparisons": "frozen multimodal reference versus each of five unimodal models",
    "classification_metric": "subject-level macro_f1",
    "regression_metric": "subject-level bounded_mae",
    "test": "Wilcoxon signed-rank",
    "multiplicity": "Holm correction separately within five classification and five regression comparisons",
    "alpha": 0.05,
    "effect_size": "rank-biserial correlation",
    "not_estimable_rule": "If all paired differences are zero or the test is not computable, report NOT_ESTIMABLE with reason and no fabricated p-value"
  },
  "interpretation": "association and predictive performance only; no physiological causality"
}

## Static tests and contract artifact audit

In [29]:
test_report = json.loads((PHASE_DIR / 'audits/phase07_contract_artifact_audit.json').read_text(encoding='utf-8'))
print(json.dumps({'static_unit_tests': test_report.get('static_unit_tests'), 'artifact_audit_result': test_report['result']}, indent=2)); assert test_report['result'] == 'PASS' and test_report.get('static_unit_tests') == 'PASS'

{
  "static_unit_tests": "PASS",
  "artifact_audit_result": "PASS"
}

## Contract Freeze execution gate

In [30]:
ready = all([contract['status'] == 'CONTRACT_FROZEN_NOT_TRAINED', test_report['result'] == 'PASS', not contract['training_executed'], not contract['outer_test_predictions_generated']])
print(json.dumps({'training_executed': 'NO', 'outer_test_predictions_generated': 'NO', 'ready_for_unimodal_execution_subject_to_notebook_persistence': ready}, indent=2)); assert ready

{
  "training_executed": "NO",
  "outer_test_predictions_generated": "NO",
  "ready_for_unimodal_execution_subject_to_notebook_persistence": true
}

# Phase 07 Unimodal Batch Execution

Executed frozen five-modality Hybrid classification and Common Encoder Ridge regression runs. Canonical OOF consolidation, ranking, and statistical analysis are not executed here.

In [31]:
execution_manifest = json.loads((PHASE_DIR / 'configs/phase07_execution_manifest.json').read_text(encoding='utf-8'))
static_audit = json.loads((PHASE_DIR / 'audits/phase07_executor_static_audit.json').read_text(encoding='utf-8'))
execution_audit = json.loads((PHASE_DIR / 'audits/phase07_unimodal_execution_artifact_audit.json').read_text(encoding='utf-8'))
print(json.dumps({'executor_static_checks': static_audit, 'dry_run': {k: static_audit[k] for k in ['classification_runs','regression_runs','total_runs','duplicate_run_identifiers']}}, indent=2)); assert static_audit['result'] == 'PASS'

{
  "executor_static_checks": {
    "phase": "07",
    "audit": "executor_static",
    "timestamp_utc": "2026-08-20T18:18:19.877580+00:00",
    "primary_sha256": "0a2aef89c01b43c3a4e5afe40b96797784627665490982731b2541f96b45fc44",
    "frozen_fold_sha256": "e4dc943af21851bace49345f6336f9c88f82613ca3a26b3c433efe7dfb041f6f",
    "classification_runs": 125,
    "regression_runs": 125,
    "total_runs": 250,
    "duplicate_run_identifiers": 0,
    "other_hdc_variants_present_in_scope": false,
    "inner_cv_or_search_present_in_execution_scope": false,
    "result": "PASS"
  },
  "dry_run": {
    "classification_runs": 125,
    "regression_runs": 125,
    "total_runs": 250,
    "duplicate_run_identifiers": 0
  }
}

## Completed model-runs

In [32]:
print(json.dumps(execution_audit['run_counts'], indent=2)); assert execution_audit['run_counts']['classification'] == execution_audit['run_counts']['regression'] == 125 and execution_audit['run_counts']['total'] == 250

{
  "classification": 125,
  "regression": 125,
  "total": 250,
  "by_modality": {
    "physiological_features": 50,
    "eye_tracking_features": 50,
    "head_movement_features": 50,
    "flight_parameter_features": 50,
    "body_movement": 50
  },
  "by_fold": {
    "1": 50,
    "2": 50,
    "3": 50,
    "4": 50,
    "5": 50
  },
  "by_seed": {
    "42": 50,
    "43": 50,
    "44": 50,
    "45": 50,
    "46": 50
  }
}

## Checkpoint, leakage, and subject-isolation audits

In [33]:
checkpoint_audit = json.loads((PHASE_DIR / 'audits/phase07_checkpoint_integrity_audit.json').read_text(encoding='utf-8'))
print(json.dumps({k: checkpoint_audit[k] for k in ['completed_checkpoints','duplicate_checkpoint_ids','all_checkpoint_integrity_pass','all_leakage_audits_pass','all_outer_subject_overlap_zero','result']}, indent=2)); assert checkpoint_audit['result'] == 'PASS'

{
  "completed_checkpoints": 250,
  "duplicate_checkpoint_ids": 0,
  "all_checkpoint_integrity_pass": true,
  "all_leakage_audits_pass": true,
  "all_outer_subject_overlap_zero": true,
  "result": "PASS"
}

## Seed-level prediction coverage

In [34]:
coverage_audit = json.loads((PHASE_DIR / 'audits/phase07_seed_level_coverage_audit.json').read_text(encoding='utf-8'))
print(json.dumps({k: coverage_audit[k] for k in ['classification_prediction_files','regression_prediction_files','classification_seed_level_rows','regression_seed_level_rows','total_seed_level_rows','result']}, indent=2)); assert coverage_audit['result'] == 'PASS'

{
  "classification_prediction_files": 125,
  "regression_prediction_files": 125,
  "classification_seed_level_rows": 10475,
  "regression_seed_level_rows": 10475,
  "total_seed_level_rows": 20950,
  "result": "PASS"
}

## Runtime and execution-state summary

In [35]:
efficiency_root = PHASE_DIR / 'results/efficiency'
efficiency_files = list(efficiency_root.rglob('*.json'))
records = [(path, json.loads(path.read_text(encoding='utf-8'))) for path in efficiency_files]
preprocessing_unique = {}
encoding_unique = {}
for path, item in records:
    relative = path.relative_to(efficiency_root)
    modality, task, filename = relative.parts
    fold = filename.split('_seed_')[0]
    seed = filename.split('_seed_')[1].split('_metrics')[0].split('_efficiency')[0]
    preprocessing_unique.setdefault((modality, fold), item['preprocessing_seconds'])
    encoding_unique.setdefault((modality, fold, seed), item['encoding_seconds'])
runtime = {'efficiency_records': len(records), 'shared_preprocessing_fits': len(preprocessing_unique), 'shared_encoder_runs': len(encoding_unique), 'preprocessing_seconds_deduplicated': sum(preprocessing_unique.values()), 'encoding_seconds_deduplicated': sum(encoding_unique.values()), 'task_training_seconds': sum(item['training_seconds'] for _, item in records), 'task_inference_seconds': sum(item['inference_seconds'] for _, item in records)}
print(json.dumps({'runtime_summary': runtime, 'execution_manifest': execution_manifest}, indent=2)); assert len(records) == 250 and len(preprocessing_unique) == 25 and len(encoding_unique) == 125

{
  "runtime_summary": {
    "efficiency_records": 250,
    "shared_preprocessing_fits": 25,
    "shared_encoder_runs": 125,
    "preprocessing_seconds_deduplicated": 0.30613739998079836,
    "encoding_seconds_deduplicated": 78.35187000001315,
    "task_training_seconds": 67.46307500029798,
    "task_inference_seconds": 0.5769908004440367
  },
  "execution_manifest": {
    "phase": "07",
    "status": "FROZEN",
    "created_at_utc": "2026-08-20T18:05:58.896065+00:00",
    "modalities": 5,
    "modality_names": [
      "physiological_features",
      "eye_tracking_features",
      "head_movement_features",
      "flight_parameter_features",
      "body_movement"
    ],
    "outer_folds": 5,
    "evaluation_seeds": [
      42,
      43,
      44,
      45,
      46
    ],
    "evaluation_seed_count": 5,
    "classification_runs": 125,
    "regression_runs": 125,
    "total_model_runs": 250,
    "checkpoint_granularity": "modality/task/fold/seed",
    "resume_policy": "reuse only audit-PASS checkpoints",
    "completed_runs": 250,
    "training_executed": true,
    "prediction_files_generated": 250,
    "oof_files_generated": 0,
    "executor_invoked": true,
    "last_updated_utc": "2026-08-20T18:21:08.667820+00:00",
    "completed_classification_runs": 125,
    "completed_regression_runs": 125,
    "executor_completed": true,
    "canonical_oof_generated": true,
    "canonical_classification_rows": 2095,
    "canonical_regression_rows": 2095,
    "finalized_at_utc": "2026-08-20T18:49:14.421635+00:00"
  }
}

## Ready for OOF consolidation

In [36]:
canonical_done = bool(execution_manifest.get('canonical_oof_generated', False))
valid_execution_state = all([execution_audit['result'] == 'PASS', execution_manifest['completed_runs'] == 250, execution_manifest['training_executed']])
ready = valid_execution_state and (execution_manifest.get('status') in ['UNIMODAL_EXECUTION_COMPLETE_PENDING_OOF_CONSOLIDATION', 'FROZEN'])
print(json.dumps({'training_executed': 'YES', 'canonical_oof_consolidation_executed': 'YES' if canonical_done else 'NO', 'lifecycle_state': execution_manifest.get('status'), 'valid_execution_lifecycle': ready}, indent=2)); assert ready

{
  "training_executed": "YES",
  "canonical_oof_consolidation_executed": "YES",
  "lifecycle_state": "FROZEN",
  "valid_execution_lifecycle": true
}

## Phase 07 Final OOF Consolidation, Modality Analysis and Freeze

This persisted section reports derived results only; it performs no training or prediction generation.

In [37]:
from pathlib import Path
import json, pandas as pd
phase07_dir = Path.cwd()
if phase07_dir.name != 'phase_07_unimodal_contribution':
    phase07_dir = Path(r'E:\hdc-vr-pilot\experiments\phase_07_unimodal_contribution')
freeze = json.loads((phase07_dir/'configs/phase07_freeze.json').read_text()) if (phase07_dir/'configs/phase07_freeze.json').exists() else {}
class_rank = pd.read_csv(phase07_dir/'results/summaries/phase07_classification_modality_ranking.csv')
reg_rank = pd.read_csv(phase07_dir/'results/summaries/phase07_regression_modality_ranking.csv')
bootstrap = pd.read_csv(phase07_dir/'results/summaries/phase07_bootstrap_confidence_intervals.csv')
friedman = pd.read_csv(phase07_dir/'results/summaries/phase07_friedman_tests.csv')
wilcoxon_holm = pd.read_csv(phase07_dir/'results/summaries/phase07_wilcoxon_holm_tests.csv')
availability = pd.read_csv(phase07_dir/'results/summaries/phase07_availability_stratified_metrics.csv')
print('Classification canonical OOF rows:', sum(1 for _ in open(phase07_dir/'results/oof/phase07_unimodal_classification_canonical_oof.csv', encoding='utf-8'))-1)
print('Regression canonical OOF rows:', sum(1 for _ in open(phase07_dir/'results/oof/phase07_unimodal_regression_canonical_oof.csv', encoding='utf-8'))-1)
display(class_rank, reg_rank, bootstrap, friedman, wilcoxon_holm, availability)
print('Figure paths:', sorted(str(p.relative_to(phase07_dir)) for p in (phase07_dir/'figures').glob('phase07_*')))
print('Best classification modality:', class_rank.iloc[0].modality)
print('Best regression modality:', reg_rank.iloc[0].modality)
print('Phase 07 status:', freeze.get('status','PENDING_FINAL_VERIFICATION'))
print('Ready for Phase 08:', freeze.get('ready_for_next_planned_phase',False))

Classification canonical OOF rows: 2095

Regression canonical OOF rows: 2095

,modality,macro_f1,balanced_accuracy,accuracy,severe_error_rate,seed_macro_f1_mean,seed_macro_f1_sample_sd,canonical_rows,rank
0,flight_parameter_features,0.863458,0.864093,0.863962,0.011933,0.823377,0.012751,419,1
1,head_movement_features,0.373296,0.375151,0.374702,0.233890,0.336912,0.024671,419,2
2,eye_tracking_features,0.346833,0.351635,0.350835,0.238663,0.345778,0.012941,419,3
3,physiological_features,0.332190,0.340745,0.341289,0.312649,0.279611,0.018598,419,4
4,body_movement,0.228379,0.245077,0.245823,0.331742,0.262964,0.015843,419,5

,modality,bounded_mae,raw_mae,bounded_rmse,bounded_r2,bounded_spearman,clipping_count,clipping_rate,seed_bounded_mae_mean,seed_bounded_mae_sample_sd,canonical_rows,rank
0,flight_parameter_features,0.261110,0.279536,0.389104,0.878647,0.931247,54,0.128878,0.273894,0.008033,419,1
1,eye_tracking_features,0.847353,0.861517,1.057002,0.104487,0.426285,26,0.062053,0.866261,0.010339,419,2
2,head_movement_features,0.890777,0.905127,1.098760,0.032332,0.354278,19,0.045346,0.918626,0.019820,419,3
3,physiological_features,1.010788,1.058605,1.291947,-0.337857,0.175152,52,0.124105,1.048331,0.026218,419,4
4,body_movement,1.026070,1.057798,1.266880,-0.286446,0.127774,43,0.102625,1.064476,0.023697,419,5

,task,modality,metric,point_estimate,ci_95_lower,ci_95_upper,n_subjects,repetitions,bootstrap_seed,resampling_unit,interval
0,classification,physiological_features,macro_f1,0.332190,0.293630,0.367828,35,2000,42,subject_id,percentile
1,classification,physiological_features,balanced_accuracy,0.340745,0.305225,0.377212,35,2000,42,subject_id,percentile
2,classification,physiological_features,severe_error_rate,0.312649,0.269004,0.355609,35,2000,42,subject_id,percentile
3,classification,eye_tracking_features,macro_f1,0.346833,0.299951,0.390278,35,2000,42,subject_id,percentile
4,classification,eye_tracking_features,balanced_accuracy,0.351635,0.307476,0.395125,35,2000,42,subject_id,percentile
5,classification,eye_tracking_features,severe_error_rate,0.238663,0.190476,0.286413,35,2000,42,subject_id,percentile
6,classification,head_movement_features,macro_f1,0.373296,0.336032,0.410682,35,2000,42,subject_id,percentile
7,classification,head_movement_features,balanced_accuracy,0.375151,0.340004,0.413042,35,2000,42,subject_id,percentile
8,classification,head_movement_features,severe_error_rate,0.233890,0.190931,0.278571,35,2000,42,subject_id,percentile
9,classification,flight_parameter_features,macro_f1,0.863458,0.801834,0.918509,35,2000,42,subject_id,percentile
10,classification,flight_parameter_features,balanced_accuracy,0.864093,0.803013,0.918847,35,2000,42,subject_id,percentile
11,classification,flight_parameter_features,severe_error_rate,0.011933,0.002386,0.026190,35,2000,42,subject_id,percentile
12,classification,body_movement,macro_f1,0.228379,0.195438,0.255354,35,2000,42,subject_id,percentile
13,classification,body_movement,balanced_accuracy,0.245077,0.220353,0.270832,35,2000,42,subject_id,percentile
14,classification,body_movement,severe_error_rate,0.331742,0.293556,0.369048,35,2000,42,subject_id,percentile
15,classification,multimodal_reference,macro_f1,0.871057,0.823087,0.914257,35,2000,42,subject_id,percentile
16,classification,multimodal_reference,balanced_accuracy,0.871236,0.823727,0.914120,35,2000,42,subject_id,percentile
17,classification,multimodal_reference,severe_error_rate,0.019093,0.004773,0.035885,35,2000,42,subject_id,percentile
18,regression,physiological_features,bounded_mae,1.010788,0.934576,1.085547,35,2000,42,subject_id,percentile
19,regression,physiological_features,bounded_rmse,1.291947,1.200964,1.378710,35,2000,42,subject_id,percentile
20,regression,eye_tracking_features,bounded_mae,0.847353,0.784116,0.910695,35,2000,42,subject_id,percentile
21,regression,eye_tracking_features,bounded_rmse,1.057002,0.978114,1.136322,35,2000,42,subject_id,percentile
22,regression,head_movement_features,bounded_mae,0.890777,0.824340,0.959102,35,2000,42,subject_id,percentile
23,regression,head_movement_features,bounded_rmse,1.098760,1.023094,1.174934,35,2000,42,subject_id,percentile
24,regression,flight_parameter_features,bounded_mae,0.261110,0.207858,0.322725,35,2000,42,subject_id,percentile
25,regression,flight_parameter_features,bounded_rmse,0.389104,0.300815,0.478717,35,2000,42,subject_id,percentile
26,regression,body_movement,bounded_mae,1.026070,0.970641,1.082850,35,2000,42,subject_id,percentile
27,regression,body_movement,bounded_rmse,1.266880,1.203255,1.331915,35,2000,42,subject_id,percentile
28,regression,multimodal_reference,bounded_mae,0.265727,0.212184,0.326712,35,2000,42,subject_id,percentile
29,regression,multimodal_reference,bounded_rmse,0.394327,0.307341,0.484085,35,2000,42,subject_id,percentile

             task       metric status  statistic       p_value  n_subjects
0  classification     macro_f1   PASS  91.690100  5.759853e-19          35
1      regression  bounded_mae   PASS  78.148571  4.296543e-16          35

,task,modality,metric,status,statistic,raw_p,effect_size_rank_biserial,effect_definition,n_subjects,holm_adjusted_p,significant_alpha_0_05
0,classification,physiological_features,macro_f1,PASS,0.0,5.820766e-11,1.000000,multimodal minus unimodal,35,2.910383e-10,True
1,classification,eye_tracking_features,macro_f1,PASS,0.0,5.820766e-11,1.000000,multimodal minus unimodal,35,2.910383e-10,True
2,classification,head_movement_features,macro_f1,PASS,0.0,5.820766e-11,1.000000,multimodal minus unimodal,35,2.910383e-10,True
3,classification,flight_parameter_features,macro_f1,PASS,71.5,8.126133e-01,0.065359,multimodal minus unimodal,35,8.126133e-01,False
4,classification,body_movement,macro_f1,PASS,0.0,5.820766e-11,1.000000,multimodal minus unimodal,35,2.910383e-10,True
5,regression,physiological_features,bounded_mae,PASS,0.0,5.820766e-11,-1.000000,multimodal minus unimodal,35,2.910383e-10,True
6,regression,eye_tracking_features,bounded_mae,PASS,0.0,5.820766e-11,-1.000000,multimodal minus unimodal,35,2.910383e-10,True
7,regression,head_movement_features,bounded_mae,PASS,0.0,5.820766e-11,-1.000000,multimodal minus unimodal,35,2.910383e-10,True
8,regression,flight_parameter_features,bounded_mae,PASS,243.0,2.449025e-01,0.228571,multimodal minus unimodal,35,2.449025e-01,False
9,regression,body_movement,bounded_mae,PASS,0.0,5.820766e-11,-1.000000,multimodal minus unimodal,35,2.910383e-10,True

,task,modality,stratum,rows,macro_f1,balanced_accuracy,accuracy,severe_error_rate,bounded_mae,raw_mae,bounded_rmse,bounded_r2,bounded_spearman,clipping_count,clipping_rate
0,classification,physiological_features,modality_available,419,0.332190,0.340745,0.341289,0.312649,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,regression,physiological_features,modality_available,419,NaN,NaN,NaN,NaN,1.010788,1.058605,1.291947,-0.337857,0.175152,52.0,0.124105
2,classification,eye_tracking_features,modality_fully_missing,14,0.093750,0.187500,0.214286,0.214286,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,classification,eye_tracking_features,modality_available,405,0.351865,0.356804,0.355556,0.239506,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,regression,eye_tracking_features,modality_fully_missing,14,NaN,NaN,NaN,NaN,1.000008,1.000008,1.210083,-0.176241,-0.156813,0.0,0.000000
5,regression,eye_tracking_features,modality_available,405,NaN,NaN,NaN,NaN,0.842077,0.856730,1.051312,0.114035,0.436933,26.0,0.064198
6,classification,head_movement_features,modality_available,419,0.373296,0.375151,0.374702,0.233890,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,regression,head_movement_features,modality_available,419,NaN,NaN,NaN,NaN,0.890777,0.905127,1.098760,0.032332,0.354278,19.0,0.045346
8,classification,flight_parameter_features,modality_available,419,0.863458,0.864093,0.863962,0.011933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,regression,flight_parameter_features,modality_available,419,NaN,NaN,NaN,NaN,0.261110,0.279536,0.389104,0.878647,0.931247,54.0,0.128878
10,classification,body_movement,modality_fully_missing,29,0.162281,0.250000,0.241379,0.517241,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,classification,body_movement,modality_available,390,0.221218,0.245307,0.246154,0.317949,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,regression,body_movement,modality_fully_missing,29,NaN,NaN,NaN,NaN,0.982760,0.982760,1.102830,-0.000835,-0.023940,0.0,0.000000
13,regression,body_movement,modality_available,390,NaN,NaN,NaN,NaN,1.029290,1.063377,1.278238,-0.307114,0.136167,43.0,0.110256

Figure paths: ['figures\\phase07_classification_confusion_matrix_panel.pdf', 'figures\\phase07_classification_confusion_matrix_panel.png', 'figures\\phase07_classification_modality_ranking.pdf', 'figures\\phase07_classification_modality_ranking.png', 'figures\\phase07_regression_modality_ranking.pdf', 'figures\\phase07_regression_modality_ranking.png', 'figures\\phase07_regression_residual_panel.pdf', 'figures\\phase07_regression_residual_panel.png', 'figures\\phase07_subject_level_performance.pdf', 'figures\\phase07_subject_level_performance.png', 'figures\\phase07_unimodal_vs_multimodal_deltas.pdf', 'figures\\phase07_unimodal_vs_multimodal_deltas.png']
Best classification modality: flight_parameter_features
Best regression modality: flight_parameter_features
Phase 07 status: FROZEN
Ready for Phase 08: True